### ISSUE TITLE
sorry to forget tell you,your demo code is wrong

### ISSUE THREAD

**Issue by wzhsh90** [shixinke/lua-resty-ip2region#3]
local location = ip2region:new({
			    file = "/the/path/to/your/project/lib/resty/ip2region/data/ip2region.db",
			    dict = "ip_data",
			    mode = "memory" -- maybe memory,binary or btree
			});
this code is wrong
the right:
local location = ip2region.new({
			    file = "/the/path/to/your/project/lib/resty/ip2region/data/ip2region.db",
			    dict = "ip_data",
			    mode = "memory" -- maybe memory,binary or btree
			});
replace  ip2region:new to  ip2region.new

![image](https://user-images.githubusercontent.com/16187191/42746135-f831f69a-8908-11e8-8cb5-48b9fbc67326.png)
![image](https://user-images.githubusercontent.com/16187191/42746145-02ddfaf8-8909-11e8-803a-0cebae3ae952.png)
the isp is messy code

**Comment by shixinke** [comment]
Thank you for discovering and reporting this issue.The document has been updated.
